/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Páginas;

import Utilitários.GameState;
import Utilitários.Personagem;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author bruno
 */
public class AtleticomgP1 extends javax.swing.JFrame {

    /**
     * Creates new form Corinthiansp1
     */
    public AtleticomgP1() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        atleticomgp1 = new javax.swing.JLabel();
        retp1 = new javax.swing.JButton();
        proxp1 = new javax.swing.JButton();
        direita = new javax.swing.JButton();
        esquerda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1400, 787));
        getContentPane().setLayout(null);

        atleticomgp1.setIcon(new javax.swing.ImageIcon("C:\\Users\\bruno\\OneDrive\\Documentos\\NetBeansProjects\\HeadFootball\\src\\main\\java\\res\\atletico-mg.jpg")); // NOI18N
        getContentPane().add(atleticomgp1);
        atleticomgp1.setBounds(0, 0, 1400, 787);

        retp1.setText("jButton1");
        retp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retp1ActionPerformed(evt);
            }
        });
        getContentPane().add(retp1);
        retp1.setBounds(390, 710, 270, 50);

        proxp1.setText("jButton2");
        proxp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proxp1ActionPerformed(evt);
            }
        });
        getContentPane().add(proxp1);
        proxp1.setBounds(730, 710, 290, 50);

        direita.setText("jButton2");
        direita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direitaActionPerformed(evt);
            }
        });
        getContentPane().add(direita);
        direita.setBounds(830, 150, 80, 110);

        esquerda.setText("jButton3");
        getContentPane().add(esquerda);
        esquerda.setBounds(491, 150, 80, 110);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void retp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retp1ActionPerformed
        new TelaInicial().setVisible(true);
        dispose();
    }//GEN-LAST:event_retp1ActionPerformed

    private void proxp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proxp1ActionPerformed
    // Verificar se o personagem "Hulk" já foi escolhido
    GameState gameState = GameState.getInstance();
    boolean hulkFoiEscolhido = false;
    
    for (Personagem personagem : gameState.getPersonagensEscolhidos()) {
        if (personagem.getNome().equals("Hulk")) {
            hulkFoiEscolhido = true;
            break; // Já encontramos o Hulk na lista, podemos sair do loop
        }
    }
    
    if (hulkFoiEscolhido) {
        JOptionPane.showMessageDialog(this, "O personagem Hulk já foi escolhido.", "Informação", JOptionPane.INFORMATION_MESSAGE);
    } else if(gameState.getPersonagensEscolhidos().size() >= 2){
        new Jogo().setVisible(true);
        dispose();
    }else{
        Personagem personagem1 = new Personagem("Hulk");
        gameState.adicionarPersonagem(personagem1);
        new Botafogop1().setVisible(true);
        dispose();
    }

    }//GEN-LAST:event_proxp1ActionPerformed

    private void direitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direitaActionPerformed
      new Botafogop1().setVisible(true);
      dispose();
    }//GEN-LAST:event_direitaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtleticomgP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtleticomgP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtleticomgP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtleticomgP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtleticomgP1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel atleticomgp1;
    private javax.swing.JButton direita;
    private javax.swing.JButton esquerda;
    private javax.swing.JButton proxp1;
    private javax.swing.JButton retp1;
    // End of variables declaration//GEN-END:variables
}
